---
# cloud-config
# multipass launch focal64 -n {{ project }} -c 2 -m 2G -d 30G --cloud-init cloud-init.yml
ssh_import_id:
  - gh: mozodev
runcmd:
  - |
    cat << 'EOF' >> ~/.env
    PHP_VERSION=7.4
    MARIADB_VERSION=10.5
    PROJECT_CODE=drupal-project
    PROJECT_ROOT=/var/www/drupal-project
    PROJECT_GITREPO=git@github.com:mozodev/drupal-project.git
    EOF
  # bootstrap
  - curl -sSL https://git.io/J3yLS | bash
  # LANG:php
  - curl -sSL https://git.io/J3MVp | bash
  # LANG:nodejs
  - curl -sSL https://git.io/J3MoH | bash
  # DB:mariadb
  - curl -sSL https://git.io/J3MKe | bash
  # APP:drupal
  - curl -sSL https://git.io/J3MKt | bash
